dist: xenial
addons:
  chrome: stable
language: node_js
branches:
  only:
  - ck/10982
  - master
  - stable
  - release
  - /^v\d+\.\d+\.\d+$/
services:
- xvfb
node_js:
- "14"
cache: yarn
before_install:
#- export START_TIME=$( date +%s )
#- export COVERALLS_SERVICE_JOB_ID=$( TRAVIS_JOB_ID )
#- export COVERALLS_SERVICE_NAME="CKEditor5 code coverage"
- npm i -g yarn
install:
- yarn install
script:
- git clone https://github.com/ckeditor/ckeditor5-dev.git --branch ck/10982 && cd ckeditor5-dev && yarn && cd packages/ckeditor5-dev-tests && yarn link && cd ../../../
- yarn link @ckeditor/ckeditor5-dev-tests
- sh ./scripts/check-manual-tests.sh -r ckeditor5 -f ckeditor5
#- ./scripts/ci/travis-check.js
#- if [[ $TRAVIS_JOB_TYPE == "Tests" && $TRAVIS_TEST_RESULT -eq 0 ]]; then ./scripts/ci/trigger-ckeditor5-continuous-integration.sh; fi
after_script:
- echo 1
#- export END_TIME=$( date +%s )
#- ckeditor5-dev-tests-notify-travis-status
#env:
#  jobs:
#  - TRAVIS_JOB_TYPE=Tests
#  - TRAVIS_JOB_TYPE=Validation
